---
title: "CFB"
output: html_document
date: "2022-09-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(cfbfastR)
```

```{r}
install.packages("cfbfastR")
```

```{r}
install.packages("tictoc")
```

```{r}
tictoc::tic()
pbp <- data.frame()
seasons <- 2014:cfbfastR:::most_recent_cfb_season()
progressr::with_progress({

  pbp <- cfbfastR::load_cfb_pbp(seasons)
})
tictoc::toc()
```

```{r}
glimpse(pbp)
```

```{r}
#which team has had the most penalties on the first play of a series?
pbp %>%
  filter(new_series == 1, drive_play_number == 1, play_type == 'Penalty', down == 1) %>%
  group_by(year) %>%
  summarize(plays = n(), games = n_distinct(game_id)) %>%
  arrange(desc(plays))
```

```{r}
logs <- read_csv("http://mattwaite.github.io/sportsdatafiles/footballlogs1121.csv")
  
head(logs)

logs <- logs %>%
  mutate(PointDifferential = TeamScore - OpponentScore)

#Create a regression investigating whether the number of penalties can predict the score differential.
fit <- lm(PointDifferential ~ Penalties, data = logs)
summary(fit)
```
  
#In a paragraph below this code block, describe the results: what is the p-value, and does it mean the results are random? Using the r-squared value, how much of the differential can be explained by penalty yards? How useful is this regression?

p-value: 0.01856
R-squared: 0.0002627 
Because our p-value is less than 0.05, we know that 








