---
title: "second_project_presentation"
output: html_document
date: "2022-12-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Loading our libraries
library(tidyverse)
library(dplyr)
library(lubridate)
library(ggrepel)
```

```{r}
#Loading the referee data and creating a dataframe with game-level data
refs <- read_csv("~/Downloads/officials_2021-22.csv")

refs <- refs %>%
  mutate(date = mdy(date))

logs_2022 <- read_csv("http://dwillis.github.io/sports-data-files/wbb_game_logs_2022.csv")

refs_and_logs <- logs_2022 %>%
  inner_join(refs, by = c('date', 'ncaa_id')) %>%
  mutate(total_fouls = pf + opp_pf)
```

```{r}
#Creating dataframes that will be easier to work with than the original data.
unique_games <- refs_and_logs %>% 
  select(-ncaa_id, -game_id) %>% 
  distinct()

games_with_refs <- unique_games %>% 
  separate(officials, c('ref1', 'ref2', 'ref3'), sep=",", fill="right") %>%
  pivot_longer(cols = c('ref1', 'ref2', 'ref3'), values_to = 'ref') %>%
  mutate(ref = str_squish(ref)) %>%
  filter(!is.na(ref)) %>%
  filter(ref != '') %>%
  mutate(total_fouls = pf + opp_pf)
  
#Maryland specific data and refs
md_refs <- games_with_refs %>%
  filter(team == 'Maryland')

md_refs_by_game <- md_refs %>% 
  group_by(ref) %>%
  summarise(games = n()) %>%
  arrange(desc(games))

md_refs_more_than_3_games <- md_refs_by_game %>%
  filter(games > 2)

#Refs dataframe with games and avg fouls (and then the top-25 referees by game) + bar chart graph
distinct_refs <- games_with_refs %>%
  group_by(ref) %>%
  summarise(total_fouls = sum(total_fouls), games = n()) %>%
  mutate(average_fouls = total_fouls/games) %>%
  arrange(desc(games))

top_25_refs_fouls_per_game <- distinct_refs %>%
  filter(games > 126)

ggplot() + 
  geom_bar(
    data=top_25_refs_fouls_per_game, 
    aes(x=reorder(ref, `average_fouls`), weight=`average_fouls`)) + 
  labs(
    title="Who Are The Most Whistle-Happy Officials?",
    subtitle = "There Are Some Referees Your Team Might Not Want To See On The Docket",
    x="Referee", 
    y="Average Fouls") + 
  theme_light() + 
  coord_flip()
```

```{r}
#Creating more dataframes with information on individual refs and charting them
fouls_by_refs <- games_with_refs %>%
  group_by(ref) %>%
  summarise(avg_fouls = mean(total_fouls), games = n()) %>%
  filter(games > 10) %>%
  arrange(desc(avg_fouls))

top_avg_fouls_by_ref <- fouls_by_refs %>%
  filter(avg_fouls > 38.3)

#Looking at the relationship of fouls by refs and number of games officiated
ggplot() + geom_point(data=fouls_by_refs, aes(x=games, y=avg_fouls)) +
  geom_smooth(data=fouls_by_refs, aes(x=games, y=avg_fouls), method="lm") +
  geom_hline(yintercept=33.8) +
  labs(
    title="The More Games One Officiates, The Less Fouls One Calls", 
    x="Games", 
    y="Average Fouls")

ggplot() + 
  geom_bar(
    data=md_refs_more_than_3_games, 
    aes(x=reorder(ref, `games`), weight=`games`)) + 
  labs(
    title="Referees Who Officiate Maryland Women's Basketball Most", 
    x="Referee", 
    y="Games") + 
  theme_light() + 
  coord_flip()

all_refs_number_of_games <- distinct_refs %>%
  filter(games > 126)

ggplot() + 
  geom_bar(
    data=all_refs_number_of_games, 
    aes(x=reorder(ref, `games`), weight=`games`)) + 
  labs(
    title="Referees Who Officiate Women's Basketball Most", 
    x="Referee", 
    y="Games") + 
  theme_light() + 
  coord_flip()
```

```{r}
#Creating a dataframe with home and away foul information for the Big Ten with charts
fouls_by_month <- refs_and_logs %>%
  mutate(month = floor_date(date, unit="months")) %>%
  group_by(month) %>%
  summarise(monthly_total = sum(pf) + sum(opp_pf), games = n()) %>%
  mutate(avg_fouls_per_month = monthly_total/games) %>%
  filter(games > 25)

big_10 <- c('Nebraska', 'Northwestern', 'Iowa', 'Illinois', 'Ohio St.', 'Maryland', 'Minnesota', 'Rutgers', 'Michigan', 'Michigan St.', 'Wisconsin', 'Purdue', 'Penn St.', 'Indiana')

fouls_by_month_and_team <- refs_and_logs %>%
  mutate(month = floor_date(date, unit="months")) %>% 
  filter(home %in% big_10) %>%
  group_by(month, home_team_name) %>%
  summarise(monthly_total = sum(pf), games = n()) %>%
  mutate(avg_fouls_per_month = monthly_total/games)

fouls_by_month_and_team_visitor <- refs_and_logs %>%
  mutate(month = floor_date(date, unit="months")) %>%
  filter(away_team_name %in% big_10) %>%
  group_by(month, away_team_name) %>%
  summarise(monthly_total = sum(opp_pf), games = n()) %>%
  mutate(avg_fouls_per_month = monthly_total/games)

ggplot() + 
  geom_hline(yintercept=16.3, color="green") + 
  geom_line(data=fouls_by_month_and_team, aes(x=month, y=avg_fouls_per_month, group=home_team_name)) + 
  scale_y_continuous(limits = c(10, 25)) + 
  facet_wrap(~home_team_name) + 
  labs(
    title="Big Ten Average Home Fouls Per Month", 
    x="Month", 
    y="Average Fouls")

ggplot() + 
  geom_hline(yintercept=16.5, color="red") + 
  geom_line(data=fouls_by_month_and_team_visitor, aes(x=month, y=avg_fouls_per_month, group=away_team_name)) + 
  scale_y_continuous(limits = c(10, 25)) + 
  facet_wrap(~away_team_name) + 
  labs(
    title="Big Ten Average Away Fouls Per Month", 
    x="Month", 
    y="Average Fouls")
```

```{r}
#Creating a dataframe with home and away foul information for the Big Ten with charts
big_east <- c('Butler', 'UConn', 'Creighton', 'Seton Hall', 'DePaul', 'Marquette', 'Providence', 'Villanova', 'Georgetown', 'Xavier', "St. John's (NY)")

big_east_fouls_by_month_and_team <- refs_and_logs %>%
  mutate(month = floor_date(date, unit="months")) %>% 
  filter(home_team_name %in% big_east) %>%
  group_by(month, home_team_name) %>%
  summarise(monthly_total = sum(pf), games = n()) %>%
  mutate(avg_fouls_per_month = monthly_total/games)

big_east_fouls_by_month_and_team_visitor <- refs_and_logs %>%
  mutate(month = floor_date(date, unit="months")) %>%
  filter(away_team_name %in% big_east) %>%
  group_by(month, away_team_name) %>%
  summarise(monthly_total = sum(opp_pf), games = n()) %>%
  mutate(avg_fouls_per_month = monthly_total/games)

ggplot() + 
  geom_hline(yintercept=14.8, color="green") + 
  geom_line(data=big_east_fouls_by_month_and_team, aes(x=month, y=avg_fouls_per_month, group=home_team_name)) + 
  scale_y_continuous(limits = c(10, 25)) + 
  facet_wrap(~home_team_name) + 
  labs(
    title="Big East Average Home Fouls Per Month", 
    x="Month", 
    y="Average Fouls")

ggplot() + 
  geom_hline(yintercept=15, color="red") + 
  geom_line(data=big_east_fouls_by_month_and_team_visitor, aes(x=month, y=avg_fouls_per_month, group=away_team_name)) + 
  scale_y_continuous(limits = c(10, 25)) + 
  facet_wrap(~away_team_name) + 
  labs(
    title="Big East Average Away Fouls Per Month", 
    x="Month", 
    y="Average Fouls")
```

```{r}
#Maryland home and away fouls by month with charts
maryland_home_fouls_by_month <- fouls_by_month_and_team %>%
  filter(home_team_name == 'Maryland')

maryland_away_fouls_by_month <- fouls_by_month_and_team_visitor %>%
  filter(away_team_name == 'Maryland')

ggplot() + 
  geom_bar(
    data=maryland_home_fouls_by_month, 
    aes(x=month, weight=`avg_fouls_per_month`)) + 
  labs(
    title="Maryland Average Home Fouls Per Month",
    subtitle="The Terps saw an uptick in fouls later in the season",
    x="Month", 
    y="Average Fouls") + 
  theme_light() +
  ylim(0, 35)

ggplot() + 
  geom_bar(
    data=maryland_away_fouls_by_month, 
    aes(x=month, weight=`avg_fouls_per_month`)) + 
  labs(
    title="Maryland Average Away Fouls Per Month", 
    subtitle="The Terps fouled more late last season",
    x="Month", 
    y="Average Fouls") + 
  theme_light() +
  ylim(0, 35)
```

```{r}
#Overall average fouls per month in WBB
ggplot() + 
  geom_bar(
    data=fouls_by_month, 
    aes(x=month, weight=`avg_fouls_per_month`)) + 
  labs(
    title="Average Fouls Per Month", 
    subtitle="Referees are more consistent than you think",
    x="Month", 
    y="Average Fouls") + 
  theme_light() +
  ylim(0, 50)
```