---
title: "volleyball.rmd"
output: html_document
date: "2022-09-28"
---

```{r}
library(tidyverse)
```


```{r setup, include=FALSE}
match_data <- read_csv("https://raw.githubusercontent.com/dwillis/NCAAWomensVolleyballData/main/data/ncaa_womens_volleyball_matchstats_2022.csv")

head(match_data)

teamquality <- match_data %>% 
  select(team, kills, digs, aces, block_solos, block_assists, b_err, team_score, opponent_score)

teamtotals <- teamquality %>% 
  group_by(team) %>% 
  summarise(
    KillsAvg = mean(kills), 
    DigsAvg = mean(digs), 
    AcesAvg = mean(aces),
    BSoloAvg = mean(block_solos),
    BAssAvg = mean(block_assists),
    BErrAvg = mean(b_err),
    TeamScoreAvg = mean(team_score),
    OppScoreAvg = mean(opponent_score),
    ) 

teamzscore <- teamtotals %>% 
  mutate(
    killszscore = as.numeric(scale(KillsAvg, center = TRUE, scale = TRUE)),
    digszscore = as.numeric(scale(DigsAvg, center = TRUE, scale = TRUE)),
    aceszscore = as.numeric(scale(AcesAvg, center = TRUE, scale = TRUE)),
    soloblockszscore = as.numeric(scale(BSoloAvg, center = TRUE, scale = TRUE)),
    blockassistzscore = as.numeric(scale(BAssAvg, center = TRUE, scale = TRUE)),
    blockerrorzscore = as.numeric(scale(BErrAvg, center = TRUE, scale = TRUE)),
    teamscorezscore = as.numeric(scale(TeamScoreAvg, center = TRUE, scale = TRUE)),
    oppscorezscore = as.numeric(scale(OppScoreAvg, center = TRUE, scale = TRUE)),
    TotalZscore = KillsAvg + DigsAvg + AcesAvg + BSoloAvg + BAssAvg + BErrAvg + TeamScoreAvg + OppScoreAvg
    ) %>% ungroup() 

head(teamzscore)

teamzscore %>% arrange(desc(TotalZscore))

teamzscore %>% 
  filter(team == "Maryland Terrapins, Terps") %>% 
  arrange(desc(TotalZscore)) %>%
  select(team, TotalZscore)
```

```{r}
perset_stats <- match_data %>% 
  mutate(
    killsperset = kills/s,
    digsperset = digs/s,
    acesperset = aces/s,
    soloblocksperset = block_solos/s,
    blockassistsperset = block_assists/s,
    blockerrorsperset = b_err/s,
    teamscoreperset = team_score/s,
    oppscoreperset = opponent_score/s
    ) %>%
  select(date, team, killsperset, digsperset, acesperset, soloblocksperset, blockassistsperset, blockerrorsperset, teamscoreperset, oppscoreperset)

head(perset_stats)

teamzscore <- perset_stats %>%
  group_by(team) %>% 
  mutate(
    killszscore = as.numeric(scale(killsperset, center = TRUE, scale = TRUE)),
    digszscore = as.numeric(scale(digsperset, center = TRUE, scale = TRUE)),
    aceszscore = as.numeric(scale(acesperset, center = TRUE, scale = TRUE)),
    soloblockszscore = as.numeric(scale(soloblocksperset, center = TRUE, scale = TRUE)),
    blockassistzscore = as.numeric(scale(blockassistsperset, center = TRUE, scale = TRUE)),
    blockerrorzscore = as.numeric(scale(blockerrorsperset, center = TRUE, scale = TRUE)),
    teamscorezscore = as.numeric(scale(teamscoreperset, center = TRUE, scale = TRUE)),
    oppscorezscore = as.numeric(scale(oppscoreperset, center = TRUE, scale = TRUE)),
    TotalZscore = killszscore + aceszscore + digszscore + soloblockszscore + blockassistzscore + blockerrorzscore + teamscorezscore + oppscorezscore
    ) %>% ungroup() 

head(teamzscore)

teamzscore %>% arrange(desc(TotalZscore))

teamzscore %>% 
  filter(team == "Maryland Terrapins, Terps") %>% 
  arrange(desc(TotalZscore)) %>%
  select(date, team, TotalZscore)
```




