---
title: "presentation.Rmd"
output: html_document
date: "2022-10-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#I'm loading the necessary libraries for this set of queries
library(baseballr)
library(dplyr)
library(ggplot2)
library(tidyr)
```

```{r}
#I'm looking at all the MLB teams
mlb_teams(season = 2022, sport_ids = c(1))
```

#Teams that "blew up" their rosters
```{r}
#Every player who logged a major-league game for the Nats in 2022
nats_od_roster_2022 <- mlb_rosters(team_id = 120, season = 2022, date = "2021-04-07", roster_type = 'fullSeason')

#Every player who logged a major-league game for the A's in 2022
athletics_od_roster_2022 <- mlb_rosters(team_id = 133, season = 2022, date = "2022-04-08", roster_type = 'fullSeason')

#Every player who logged a major-league game for the Reds in 2022
reds_od_roster_2022 <- mlb_rosters(team_id = 113, season = 2022, date = "2022-04-08", roster_type = 'fullSeason')
```

#"Sellers" at the trade deadline
```{r}
nats_departures <- nats_od_roster_2022 %>%
  group_by(status_description) %>%
  summarise(count = n()) %>% 
  mutate(team = 'Nats')

athletics_departures <- athletics_od_roster_2022 %>%
  group_by(status_description) %>%
  summarise(count = n()) %>% 
  mutate(team = 'As')

reds_departures <- reds_od_roster_2022 %>%
  group_by(status_description) %>%
  summarise(count = n()) %>% 
  mutate(team = 'Reds')
```

```{r}
#Combined sellers dataframe
combined_sellers <- bind_rows(nats_departures, athletics_departures, reds_departures)
```

```{r}
#Stacked bar chart showing the player status descriptions for the Nats, A's and Reds
ggplot() + 
  geom_bar(data=combined_sellers, aes(x=team, weight=count, fill=status_description)) +
  coord_flip() +
   labs(title="How do the Terps compare in aces per match against elite Big Ten teams?", subtitle="Maryland setter Sydney Dowler is one of the best servers in the conference.", caption="Source: Baseball-Reference | By Ian Decker")
```

#AL teams expected to compete for the World Series
```{r}
#Every player who logged a major-league game for the Astros in 2022
astros_od_roster_2022 <- mlb_rosters(team_id = 117, season = 2022, date = "2022-04-07", roster_type = 'fullSeason')

#Every player who logged a major-league game for the Yankees in 2022
yankees_od_roster_2022 <- mlb_rosters(team_id = 147, season = 2022, date = "2022-04-07", roster_type = 'fullSeason')
```

#NL Teams expected to compete for the World Series 
```{r}
#Every player who logged a major-league game for the Dodgers in 2022
dodgers_od_roster_2022 <- mlb_rosters(team_id = 119, season = 2022, date = "2022-04-08", roster_type = 'fullSeason')

#Every player who logged a major-league game for the Mets in 2022
mets_od_roster_2022 <- mlb_rosters(team_id = 121, season = 2022, date = "2022-04-07", roster_type = 'fullSeason')
```

#"Buyers" at the trade deadline
```{r}
astros_departures <- astros_od_roster_2022 %>%
  group_by(status_description) %>%
  summarise(count = n()) %>% 
  mutate(team = 'Astros')

yankees_departures <- yankees_od_roster_2022 %>%
  group_by(status_description) %>%
  summarise(count = n()) %>% 
  mutate(team = 'Yankees')

dodgers_departures <- dodgers_od_roster_2022 %>%
  group_by(status_description) %>%
  summarise(count = n()) %>% 
  mutate(team = 'Dodgers')

mets_departures <- mets_od_roster_2022 %>%
  group_by(status_description) %>%
  summarise(count = n()) %>% 
  mutate(team = 'Mets')
```

```{r}
#Combined buyers dataframe
combined_buyers <- bind_rows(astros_departures, yankees_departures, dodgers_departures, mets_departures)
```

```{r}
#Stacked bar chart showing the player status descriptions for the Astros, Yankees, Dodgers and Mets
ggplot() + 
  geom_bar(data=combined_buyers, aes(x=team, weight=count, fill=status_description)) +
  coord_flip() +
   labs(title="How do the Terps compare in aces per match against elite Big Ten teams?", subtitle="Maryland setter Sydney Dowler is one of the best servers in the conference.", caption="Source: Baseball-Reference | By Ian Decker")
```

```{r}
nats_2005_record <- bref_team_results('WSN', 2005) %>%
    filter(Gm == '162')
nats_2006_record <- bref_team_results('WSN', 2006) %>%
    filter(Gm == '162')
nats_2007_record <- bref_team_results('WSN', 2007) %>%
    filter(Gm == '162')
nats_2008_record <- bref_team_results('WSN', 2008) %>%
    filter(Gm == '161')
nats_2009_record <- bref_team_results('WSN', 2009) %>%
    filter(Gm == '162')
nats_2010_record <- bref_team_results('WSN', 2010) %>%
    filter(Gm == '162')
nats_2011_record <- bref_team_results('WSN', 2011) %>%
    filter(Gm == '161')
nats_2012_record <- bref_team_results('WSN', 2012) %>%
    filter(Gm == '162')
nats_2013_record <- bref_team_results('WSN', 2013) %>%
    filter(Gm == '162')
nats_2014_record <- bref_team_results('WSN', 2014) %>%
    filter(Gm == '162')
nats_2015_record <- bref_team_results('WSN', 2015) %>%
    filter(Gm == '162')
nats_2016_record <- bref_team_results('WSN', 2016) %>%
    filter(Gm == '161')
nats_2017_record <- bref_team_results('WSN', 2017) %>%
    filter(Gm == '162')
nats_2018_record <- bref_team_results('WSN', 2018) %>%
    filter(Gm == '162')
nats_2019_record <- bref_team_results('WSN', 2019) %>%
    filter(Gm == '162')
nats_2020_record <- bref_team_results('WSN', 2020) %>%
    filter(Gm == '60')
nats_2021_record <- bref_team_results('WSN', 2021) %>%
    filter(Gm == '162')
nats_2022_record <- bref_team_results('WSN', 2022) %>%
    filter(Gm == '162')  

nats_overall_record <- bind_rows(nats_2005_record, nats_2006_record, nats_2007_record, nats_2008_record,nats_2009_record, nats_2010_record, nats_2011_record, nats_2012_record, nats_2013_record, nats_2014_record, nats_2015_record, nats_2016_record, nats_2017_record, nats_2018_record, nats_2019_record, nats_2020_record, nats_2021_record, nats_2022_record)

#Separating the Record column into Wins and Losses
nats_record_wins_losses_separate <- separate(nats_overall_record, col=Record, into=c('Wins', 'Losses'), sep='-') %>%
  mutate(Wins = as.numeric(Wins), Losses = as.numeric(Losses)) %>%
  mutate(win_percentage = (Wins/(Wins+Losses)*100))

#Graphing the wins by year using a line chart
ggplot(nats_record_wins_losses_separate, aes(x=Year, y=win_percentage, group=Tm)) +         
  geom_line() +
  geom_point() +
   labs(title="How do the Terps compare in aces per match against elite Big Ten teams?", subtitle="Maryland setter Sydney Dowler is one of the best servers in the conference.", caption="Source: Baseball-Reference | By Ian Decker")
```


#Narrative
Do we have an inflated sense of roster blowing up?
What happens to players when they depart






